### ISSUE TITLE
Image not compiling correctly

### ISSUE THREAD

**Issue by SpencerC** [stylus/nib#189]
``` stylus
.leather
  image "https://local-assets.pksy.io/img/dark-leather.png" 256pt 256pt
  //image "/img/dark-leather.png" 256pt 256pt
  background-position top center
```

Compiles to:

``` css
@import url("http://fonts.googleapis.com/css?family=Gudea:400,700,400italic");
.leather {
  background-image: url("https://local-assets.pksy.io/img/dark-leather.png");
  background-position: top center;
}
@media all and (-webkit-min-device-pixel-ratio: 1.5) {
  .leather {
    background-image: url("https:/local-assets.pksy.io/img/dark-leather@2x.png");
    -webkit-background-size: 256pt 256pt;
    -moz-background-size: 256pt 256pt;
    background-size: 256pt 256pt;
  }
}
```

Note the dropped slash in the @2x URLs. Is there a work around?
